run_Cloaders_offarray <- function() {
  Cloaders <- attr( sys.function(), 'Cloaders')
  for( iCloader in names( Cloaders)) {
    flypatch <- system.file( sprintf( 'R/Cloaders_%s.R', iCloader), package='offarray')
    if( nzchar( flypatch)) { # empty string if not
      # use that instead of built-in, eg if debugging
      source( flypatch, local=asNamespace( 'offarray'), echo=FALSE, verbose=FALSE)
    } else {
      eval( Cloaders[[ iCloader]], asNamespace( 'offarray'))
    }
  }
}
attr( run_Cloaders_offarray, 'Cloaders') <- list( NULL# ))
,offarray = quote({
TRUE
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ismis_dotlist <- function(dots) {
    .Call(`_offarray_ismis_dotlist`, dots)
}

indfix <- function(dots, dotmiss, dimx, offs, slice, nooff) {
    .Call(`_offarray_indfix`, dots, dotmiss, dimx, offs, slice, nooff)
}

})
)[-1]

